<?php


$sortOptions = ['name_asc' => 'Name (A-Z)', 'name_desc' => 'Name (Z-A)', 'price_asc' => 'Price (Low to High)', 'price_desc' => 'Price (High to Low)'];
?>
<!-- <style>
    .card-img-top {
        width: 100%;
        height: 250px;
        /* Adjust height as needed */
        object-fit: cover;
        /* Ensures images scale and crop nicely */
    }
</style> -->

<div class="container m-4">
    <div class="row"> 
        <!-- Filter Sidebar -->
       <?php $this->getChildHtml('filter');?>
       <?php $this->getChildHtml('product');?>
       
        <!-- Product Listing -->
     </div>
</div> 

