<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customer Login</title>
</head>
<body>

    <h2>Customer Login</h2>
    
    <form action="<?php echo $this->getUrl("*/*/validat")?>" method="POST">
        <label for="email">Email:</label>
        <input type="email" id="email" name="customer[email]" required>
        <br><br>

        <label for="password">Password:</label>
        <input type="password" id="password" name="customer[password]" required>
        <br><br>

        <a href="<?php echo $this->getUrl('customer/Account/registration') ?>"><h5>User Registretion</h5></a>
        <a href="<?php echo $this->getUrl('customer/Account/forget') ?>"><h5>forgate via otp</h5></a>
        <button type="submit">Login</button>
    </form>

</body>
</html>