<h2 class="text-center m-3">Category List</h2>
<div class="table-container">
    <table>
        <thead>
            <tr class="text-center">
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Parent Category Id</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php $catdata = $this->getCategories(); ?>
            <?php foreach ($catdata as $catdata): ?>
                <tr>
                    <td><?php echo ($catdata->getCategoryId()); ?></td>
                    <td><?php echo ($catdata->getName()); ?></td>
                    <td><?php echo ($catdata->getDescription()); ?></td>
                    <td><?php echo ($catdata->getParentId()); ?></td>
                    <td>
                        <!-- Edit Link -->
                        <a href="<?php echo $this->getUrl('catalog/category/new') . '/?edit_id=' . $catdata->getCategoryId(); ?>"
                         class="btn btn-primary"
                        >Edit</a>

                        <!-- Delete Link with Confirmation -->
                        <a href="<?php echo $this->getUrl('catalog/category/delete') . '/?delete_id=' . $catdata->getCategoryId(); ?>"
                            class="btn btn-danger"
                            onclick="return confirm('Are you sure you want to delete this item?');">
                            Delete
                        </a>

                    </td>
                </tr>
            <?php endforeach ?>

        </tbody>
    </table>
</div>