<style>
    table,
    td {
        border: 1px solid black;
        border-collapse: collapse;
    }

    td {
        padding: 8px;
        vertical-align: top;
        min-width: 150px;
    }

    .input-container {
        display: flex;
        gap: 6px;
        margin-top: 5px;
    }

    .control-panel {
        margin-bottom: 15px;
    }
</style>



<?php
$ticket = $this->getTicket();
$tableArray = $this->dataArray();
$tree = $this->buildTree($tableArray);
echo $this->render($tree, $ticket);
?>

<button onclick="save()">saveAll</button>
<form method="GET" action="<?php echo $this->getUrl('*/*/*') . '/' ?>">
    <textarea name="show" hidden>1</textarea>
    <textarea name="ticket_id" hidden><?php echo $this->getId() ?></textarea>
    <button type="submit">show complited</button>
</form>
<form method="GET" action="<?php echo $this->getUrl('*/*/*') . '/' ?>">
    <textarea name="ticket_id" hidden><?php echo $this->getId() ?></textarea>
    <button type="submit">hide complited</button>
</form>

<span id="tId" hidden><?php echo $this->getId() ?></span>


<!-- <script defer>
    
</script> -->