<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- jQuery 3.7.1 (latest stable version) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>


    <?php
    foreach ($this->getJs() as $js): ?>
        <script src="<?php echo Mage::getBaseUrl() . "js/" . $js ?>"></script>

    <?php endforeach; ?>

    <?php foreach ($this->getCss() as $css): ?>

        <link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl() . "css/" . $css ?>" />
    <?php endforeach; ?>
</head>